import assert from "node:assert/strict";
import test from "node:test";
import express from "express";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { temporaryDirectory } from "../testing/testSupport.js";
import { SqliteStore } from "../storage/sqliteStore.js";
import { WorkspaceService } from "../services/workspaceService.js";
import { AccessService } from "../services/accessService.js";
import { createWorkbenchUpdateRouter } from "./workbenchUpdateRoutes.js";
import { atomicJson } from "../runtime/mcpReload.js";
import { upgradeStatusSchema, runtimeReleaseSchema, upgradeRecordSchema } from "../domain/workbenchUpdateContracts.js";
import { HttpError } from "../errors.js";
import { createAiOpenApi } from "../ai/openapi.js";
import { aiOperations, AI_CONTRACT_VERSION } from "../ai/operations.js";

test("升级回执管理员专用；普通用户只读release，不泄露进程/运维信息；原ID重复读取无副作用",async t=>{
  let store: SqliteStore | undefined, workspace: WorkspaceService | undefined;
  const root=await temporaryDirectory(t,async()=>{await workspace?.shutdown();store?.close();});
  store=new SqliteStore(path.join(root,"zane.db"));workspace=new WorkspaceService(store,path.join(root,"workspace.json"));
  const access=new AccessService(store,workspace,"");
  await access.create({userId:randomUUID(),username:"update-admin",displayName:"管理",role:"admin",password:"isolated-password-2026"});
  await access.create({userId:randomUUID(),username:"update-user",displayName:"用户",role:"user",password:"isolated-password-2026"});
  const admin=(await access.login("update-admin","isolated-password-2026")).token, user=(await access.login("update-user","isolated-password-2026")).token;
  const app=express();app.use(access.middleware(async()=>root));app.use(createWorkbenchUpdateRouter(root,"release-id",true));
  app.use((error:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>res.status(error instanceof HttpError?error.status:500).json({code:error instanceof HttpError?error.code:"INTERNAL_ERROR"}));
  const server=app.listen(0,"127.0.0.1");await new Promise<void>(resolve=>server.once("listening",resolve));t.after(()=>new Promise<void>(resolve=>{server.close(()=>resolve());server.closeAllConnections();}));
  const base="http://127.0.0.1:"+(server.address() as {port:number}).port;
  const request=(route:string,token="")=>fetch(base+route,{headers:token?{Authorization:"Bearer "+token}:{}});
  assert.equal((await request("/api/v1/self/runtime-release")).status,401);
  const version=await request("/api/v1/self/runtime-release",user);assert.equal(version.status,200);assert.equal(version.headers.get("cache-control"),"no-store");
  assert.deepEqual(runtimeReleaseSchema.parse(await version.json()),{releaseId:"release-id",contractVersion:AI_CONTRACT_VERSION,environment:"production",automaticRefresh:false});
  assert.equal((await request("/api/v1/maintenance/upgrade",user)).status,403);
  assert.equal(upgradeStatusSchema.parse(await (await request("/api/v1/maintenance/upgrade",admin)).json()).operation,null);
  const operationId=randomUUID(),now=new Date().toISOString(), record=upgradeRecordSchema.parse({schemaVersion:1,operationId,revision:4,state:"waiting",createdAt:now,updatedAt:now,releaseId:operationId,message:"等待审核",checkPassed:true,blocked:{unfinished:{waiting:1}},nextAction:"wait_for_idle_or_cancel"});
  const file=path.join(root,"maintenance/upgrades",operationId+".json");await atomicJson(file,record);await atomicJson(path.join(root,"maintenance/upgrades/latest.json"),{operationId});
  const before=await readFile(file,"utf8");
  for(let attempt=0;attempt<2;attempt++) assert.deepEqual(upgradeStatusSchema.parse(await (await request("/api/v1/maintenance/upgrade?operationId="+operationId,admin)).json()).operation,record);
  assert.equal(await readFile(file,"utf8"),before);assert.equal(store.listRuns(root).runs.length,0);
  assert.equal((await request("/api/v1/maintenance/upgrade?operationId="+randomUUID(),admin)).status,404);
  assert.equal((await request("/api/v1/maintenance/upgrade?operationId=bad",admin)).status,400);
  assert.equal((await request("/api/v1/maintenance/upgrade?operationId="+operationId+"&operationId="+operationId,admin)).status,400);
  const specification=createAiOpenApi() as any;
  assert.ok(specification.components.schemas.WorkbenchUpgradeStatus);
  assert.ok(specification.components.schemas.RuntimeRelease);
  assert.equal(aiOperations.find(op=>op.name==="get_workbench_upgrade")?.effect,"read");
  assert.equal(aiOperations.find(op=>op.name==="get_runtime_release")?.access,"authenticated");
});
