import { useEffect, useState } from "react";
import { accessApi, jsonBody, type AccessPage } from "../lib/accessApi";
interface Token { id:string;revision:number;name:string;createdAt:string;expiresAt:string;revoked:boolean }
export default function AccountTokens() {
  const [tokens,setTokens] = useState<Token[]>([]); const [cursor,setCursor] = useState<string>(); const [name,setName] = useState("AI 助手"); const [secret,setSecret] = useState(""); const [error,setError] = useState(""); const [busy,setBusy] = useState(false);
  async function load(next?:string) { try { const page = await accessApi<AccessPage<Token>>("/api/v1/self/tokens" + (next ? "?cursor=" + encodeURIComponent(next) : "")); setTokens(current => next ? [...current,...page.items] : page.items); setCursor(page.nextCursor); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); },[]);
  async function create() { setBusy(true); setError(""); const tokenId = crypto.randomUUID(); try { const result = await accessApi<{token:string}>("/api/v1/self/tokens",jsonBody({tokenId,name})); setSecret(result.token); await load(); } catch (e) { setError((e as Error).message + " 凭证ID：" + tokenId + "。密钥只返回一次，若回执丢失请刷新列表找到该ID并吊销。"); } finally { setBusy(false); } }
  async function revoke(token:Token) { setBusy(true); try { await accessApi("/api/v1/self/tokens/" + token.id + "/revoke",jsonBody({revision:token.revision})); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <section className="access-card"><h2>AI 接入凭证</h2><p>AI 使用你的身份与当前场景权限。密钥有效期90天，只显示一次；不要发给其他用户。</p>{error && <p role="alert" className="access-error">{error}</p>}<div className="access-inline"><input aria-label="凭证名称" className="text-input" value={name} onChange={e => setName(e.target.value)} /><button className="button button-dark" disabled={busy || !name.trim()} onClick={() => void create()}>创建凭证</button></div>{secret && <div className="access-secret"><strong>立即安全保存，关闭后不能回读</strong><code>{secret}</code><p>MCP 环境变量：ZANE_BASE_URL 为工作台地址，ZANE_API_TOKEN 为此密钥。</p><button className="button button-outline" onClick={() => setSecret("")}>我已保存，隐藏密钥</button></div>}<ul className="access-list">{tokens.map(token => <li key={token.id}><span>{token.name}<small>{token.id} · {token.revoked ? "已吊销" : "有效期至 " + new Date(token.expiresAt).toLocaleString()}</small></span><button className="button button-outline" disabled={busy || token.revoked} onClick={() => void revoke(token)}>吊销</button></li>)}</ul>{cursor && <button className="button button-outline" onClick={() => void load(cursor)}>加载更多</button>}</section>;
}
