import { multipartImagesValueSchema, responseImagesValueSchema } from "../execution/thirdPartyMediaContract.js";
import { comfyOutputMediaCountsValueSchema } from "../domain/comfyOutputContracts.js";
import type { CapabilityDefinition } from "./contracts.js";
const ports = { inputs: "ports", outputs: "ports", editablePorts: true } as const;
const bindings = { inputs: "bindings", outputs: "bindings", bindings: true } as const;
export const builtinCapabilities: CapabilityDefinition[] = [
  { id: "core.hermes", version: "1", usage: {"tier":"basic","whenToUse":"生成、分析或改写文本/结构化数据；场景差异通过 Profile、提示词和输入输出配置表达。"}, label: "Hermes Agent", description: "调用已配置的 Hermes Profile 生成文本或结构化结果。", category: "模型", legacy: { kind: "hermes" }, inputs: [], outputs: [], config: [], editor: { ...ports, profile: true, prompt: true }, result: { renderer: "auto" } },
  { id: "core.comfyui", version: "1", usage: {"tier":"basic","whenToUse":"常规图片、视频或音频生成；选择工作流并绑定节点，批量生成复用步骤级逐项执行。"}, label: "ComfyUI", description: "执行 ComfyUI 工作流，只绑定普通图片/音频/视频列表；上游业务分类通过基础媒体选择与合并生成物理列表。旧同端口分类绑定保持按顺序追加兼容，不新增分类端口。", category: "模型", legacy: { kind: "comfyui" }, inputs: [], outputs: [], config: [{ key: "outputMediaCounts", label: "媒体输出准确数量（可选）", type: "json", valueSchema: comfyOutputMediaCountsValueSchema, description: "按已声明输出key约束每次/逐项执行的媒体数量，例如{images:1}；0..144，最多64个输出。省略不改变旧流程，不截断/补齐。" }], editor: bindings, result: { renderer: "auto" } },
  { id: "core.http_request", version: "2", usage: { tier: "basic", whenToUse: "调用公网 HTTP/HTTPS 第三方 JSON API，传入文本/JSON并读取 JSON/文本响应；例如提交生图任务或查询任务状态。", basicAlternative: "本机 ComfyUI 工作流优先使用 core.comfyui。此能力支持JSON或multipart图片上传与base64图片响应归档；异步轮询和音视频附件需其他通用步骤或适配。" }, label: "第三方接口请求", description: "向固定公网 HTTP/HTTPS 地址发送JSON或multipart请求，输出状态码、JSON/文本响应及可选图片列表；默认只发一次、不跟随重定向，可显式配置0–5次重试只补偿网络失败、超时和HTTP 408/429/500/502/503/504。HTTP为明文传输，API密钥不经TLS保护，能使用HTTPS时优先HTTPS。", category: "接口", legacy: { kind: "capability" }, inputs: [], outputs: [{ key: "response", label: "响应内容", type: "json", required: false, description: "JSON响应为原生值；非JSON响应为文本；空响应为null。只关心图片的场景可以不声明此输出。" }, { key: "status", label: "HTTP状态码", type: "number", required: false, description: "HTTP状态码；只关心图片的场景可以不声明此输出。" }, { key: "images", label: "返回图片", type: "image_list", required: false, description: "启用responseImages时解码并归档PNG/JPEG/WebP；无映射不产生该输出。生图场景建议只声明此输出。" }], config: [
    { key: "url", label: "第三方接口地址", type: "text", required: true, placeholder: "https://api.example.com/v1/images/generations", description: "支持HTTP/HTTPS公网地址与任意端口（公网域名或公网IP字面量）；拒绝本机/内网/回环/链路本地/保留IP、URL凭据、敏感查询参数和动态URL，域名解析结果同样逐一校验。HTTP为明文传输，API密钥不经TLS保护，能使用HTTPS时优先HTTPS。" },
    { key: "method", label: "请求方法", type: "select", defaultValue: "POST", options: ["GET", "POST", "PUT", "PATCH", "DELETE"] },
    { key: "headers", label: "附加请求头", type: "json", defaultValue: {}, valueSchema: { type: "object", additionalProperties: { type: "string" } }, description: "仅填写非敏感的固定请求头；鉴权头、Cookie、Host和Content-Length会被拒绝，Content-Type由正文格式自动设置。" },
    { key: "apiKeyEnv", label: "API密钥环境变量名", type: "text", placeholder: "IMAGE_API_KEY", description: "可选。密钥值只从工作台服务进程环境读取，不保存在场景、运行记录或AI配置中。" },
    { key: "apiKeyHeader", label: "密钥请求头", type: "text", defaultValue: "Authorization", description: "apiKeyEnv非空时使用；例如Authorization或X-API-Key。" },
    { key: "apiKeyPrefix", label: "密钥前缀", type: "text", defaultValue: "Bearer ", description: "例如Bearer后带空格；API Key请求头可留空。" },
    { key: "bodyFormat", label: "正文格式", type: "select", defaultValue: "json", options: ["json", "multipart"], description: "json兼容原有请求；multipart用于普通标量字段和已授权图片上传。" },
    { key: "multipartImages", label: "图片上传映射", type: "json", valueSchema: multipartImagesValueSchema, description: "例如[{inputKey:product_images,fieldName:image[]}]；只读取当前运行的授权图片归档，按顺序重复表单字段，最多16张、每张20MB、总正文64MB。不接受任意路径或预览URL。" },
    { key: "responseImages", label: "图片响应映射", type: "json", valueSchema: responseImagesValueSchema, description: "例如{path:data,base64Field:b64_json,expectedCount:1}。JSON列表中的base64解码为images；原字段替换为明确省略标记，响应上限64MB。不下载远程图片URL。" },
    { key: "bodyTemplate", label: "JSON请求正文", type: "json", valueSchema: { type: ["object", "array"], description: "JSON值中的{{输入key}}引用声明的步骤输入；单独占位符保留原类型。" }, placeholder: "{\n  \"prompt\": \"{{prompt}}\"\n}", description: "可选JSON对象/数组；占位符只能引用本步骤输入。JSON/表单文本字段最多256KB；multipart仅支持标量字段对象，GET不能带正文。" },
    { key: "timeoutSeconds", label: "请求超时（秒）", type: "number", defaultValue: 120, description: "1–600秒；单次尝试的DNS解析和请求共用此时限；超长请求会占用运行槽位，请按供应商实际耗时设置。" },
    { key: "retries", label: "重试次数", type: "number", defaultValue: 0, description: "0–5次；首次失败后的额外尝试次数。只对网络失败、请求超时和HTTP 408/429/500/502/503/504重试；4xx业务错误、无效JSON、响应过大、图片解码失败、非公网地址与密钥缺失等确定性错误立即失败。每次重试都重发同一请求，供应商可能重复计费或重复变更状态；省略或填0等于只发一次，不改变既有发布快照行为。" },
    { key: "retryDelaySeconds", label: "重试间隔（秒）", type: "number", defaultValue: 2, description: "0–30秒；第n次重试前等待 间隔×2^(n-1) 秒，单次等待不超过60秒。retries为0时不起作用；取消运行会立即中断等待，不发出后续请求。" },
  ], editor: { inputs: "ports", outputs: "ports", editablePorts: true, editableInputs: true, editableOutputs: false }, result: { renderer: "json" } },
  { id: "core.manual", version: "1", usage: {"tier":"basic","whenToUse":"传递输入或前序结果，不调用模型。"}, label: "数据传递", description: "把已填写的步骤输入按同名输出传递，不调用外部服务。", category: "数据", legacy: { kind: "manual" }, inputs: [], outputs: [], config: [], editor: ports, result: { renderer: "auto" } },
  { id: "core.condition", version: "1", usage: {"tier":"basic","whenToUse":"比较输入或前序结果；配合通用条件执行控制后续步骤。"}, label: "条件判断", description: "比较输入或前序结果，输出布尔判断。", category: "控制", legacy: { kind: "control" }, inputs: [], outputs: [{ key: "result", label: "判断结果", type: "boolean" }], config: [], editor: { inputs: "ports", outputs: "ports", condition: true }, result: { renderer: "json" } },
  { id: "comfyui.h3_long_video", version: "1", usage: {"tier":"specialized","whenToUse":"确实需要 H3 长视频的音频时间计划、多段提示词注入和参考图适配时使用。","basicAlternative":"普通短片先用 ComfyUI 节点绑定；多片段用通用逐项执行加本地视频拼接，不能自动等价替代 H3 时间轴适配。"}, label: "H3 长视频", description: "按计划与提示词表适配 H3 视频工作流。", category: "视频", legacy: { kind: "comfyui", adapter: "h3_long_video" }, inputs: [], outputs: [{ key: "applied_prompts", label: "已应用提示词", type: "json" }], config: [
    { key: "planRef", path: "comfyui.h3LongVideo.planRef", label: "分镜计划", type: "reference", required: true },
    { key: "promptRowsRef", path: "comfyui.h3LongVideo.promptRowsRef", label: "提示词表", type: "reference", required: true },
    { key: "referenceImagesRef", path: "comfyui.h3LongVideo.referenceImagesRef", label: "参考图片", type: "reference", required: true },
    { key: "materialNoteRef", path: "comfyui.h3LongVideo.materialNoteRef", label: "素材说明", type: "reference" },
  ], editor: { ...bindings, bindingTypes: [{ direction: "output", nodeType: "VHS_VideoCombine", property: "Filenames", type: "video_list" }] }, result: { renderer: "auto" } },
  { id: "comfyui.commerce_pack", version: "1", usage: {"tier":"specialized","compatibilityOnly":true,"whenToUse":"仅兼容已有电商图包快照和图包下载协议；新场景不再依赖此整包执行器。","basicAlternative":"新图包用 Hermes/文本模板 + ComfyUI（需要生成时）+ 图片画布与排版 + 通用逐项执行；平台尺寸/文案/清单作为配置和普通JSON输出。"}, label: "电商图包（旧版兼容）", description: "仅兼容旧图包流程和清单协议；排版已复用基础图片能力，新场景使用基础组合。", category: "图片", legacy: { kind: "comfyui", adapter: "commerce_pack" }, inputs: [], outputs: [{ key: "commerce_manifest", label: "图包清单", type: "json" }], config: [], editor: { ...bindings, inputs: "ports" }, result: { renderer: "auto" } },
  { id: "comfyui.long_text_video", version: "1", usage: {"tier":"specialized","whenToUse":"确实需要 H3 分镜时长/帧数校验、人物场景道具音色的逐镜素材映射和声音约束时使用；不是通用逐项生成的必需步骤。","basicAlternative":"普通分镜视频用 Hermes + 媒体引用选择 + ComfyUI 逐项绑定 + 本地视频拼接；只保留 H3 特有的帧网格、段落协议和原生音频规则适配。"}, label: "H3 原生有声适配", description: "保留旧 long_text_video 标识；适配 H3 帧数、六段提示词与原生声音规则。可选步骤输入prompts为按Writer分镜顺序排列的AIXG提示词字符串数组（1..360项，每项1..16000字），先全列表校验再只注入prompt，不修改Writer元数据；省略该输入保留旧inline prompt协议。逐项转换/执行复用基础Hermes与通用流程。", category: "视频", legacy: { kind: "comfyui", adapter: "long_text_video" }, inputs: [], outputs: [{ key: "applied_shot", label: "已应用镜头", type: "json" }], config: [], editor: { ...bindings, inputs: "ports", outputs: "ports", editablePorts: true }, result: { renderer: "auto" } },
  { id: "media.video_concat", version: "1", usage: {"tier":"basic","whenToUse":"把任意场景的视频片段按顺序本地合成并保留原声，不调用生成模型。"}, label: "本地视频拼接", description: "本机 FFmpeg 按顺序拼接片段，保留原生声音，不调用生成服务。", category: "视频", legacy: { kind: "comfyui", adapter: "video_concat" }, inputs: [], outputs: [], config: [], editor: ports, result: { renderer: "media" } },
];
