import { comfyOutputMediaCountsValueSchema } from "../domain/comfyOutputContracts.js";
import type { CapabilityDefinition } from "./contracts.js";
const ports = { inputs: "ports", outputs: "ports", editablePorts: true } as const;
const bindings = { inputs: "bindings", outputs: "bindings", bindings: true } as const;
export const builtinCapabilities: CapabilityDefinition[] = [
  { id: "core.hermes", version: "1", usage: {"tier":"basic","whenToUse":"生成、分析或改写文本/结构化数据；场景差异通过 Profile、提示词和输入输出配置表达。"}, label: "Hermes Agent", description: "调用已配置的 Hermes Profile 生成文本或结构化结果。", category: "模型", legacy: { kind: "hermes" }, inputs: [], outputs: [], config: [], editor: { ...ports, profile: true, prompt: true }, result: { renderer: "auto" } },
  { id: "core.comfyui", version: "1", usage: {"tier":"basic","whenToUse":"常规图片、视频或音频生成；选择工作流并绑定节点，批量生成复用步骤级逐项执行。"}, label: "ComfyUI", description: "执行 ComfyUI 工作流，只绑定普通图片/音频/视频列表；上游业务分类通过基础媒体选择与合并生成物理列表。旧同端口分类绑定保持按顺序追加兼容，不新增分类端口。", category: "模型", legacy: { kind: "comfyui" }, inputs: [], outputs: [], config: [{ key: "outputMediaCounts", label: "媒体输出准确数量（可选）", type: "json", valueSchema: comfyOutputMediaCountsValueSchema, description: "按已声明输出key约束每次/逐项执行的媒体数量，例如{images:1}；0..144，最多64个输出。省略不改变旧流程，不截断/补齐。" }], editor: bindings, result: { renderer: "auto" } },
  { id: "core.manual", version: "1", usage: {"tier":"basic","whenToUse":"传递输入或前序结果，不调用模型。"}, label: "数据传递", description: "把已填写的步骤输入按同名输出传递，不调用外部服务。", category: "数据", legacy: { kind: "manual" }, inputs: [], outputs: [], config: [], editor: ports, result: { renderer: "auto" } },
  { id: "core.condition", version: "1", usage: {"tier":"basic","whenToUse":"比较输入或前序结果；配合通用条件执行控制后续步骤。"}, label: "条件判断", description: "比较输入或前序结果，输出布尔判断。", category: "控制", legacy: { kind: "control" }, inputs: [], outputs: [{ key: "result", label: "判断结果", type: "boolean" }], config: [], editor: { inputs: "ports", outputs: "ports", condition: true }, result: { renderer: "json" } },
  { id: "comfyui.h3_long_video", version: "1", usage: {"tier":"specialized","whenToUse":"确实需要 H3 长视频的音频时间计划、多段提示词注入和参考图适配时使用。","basicAlternative":"普通短片先用 ComfyUI 节点绑定；多片段用通用逐项执行加本地视频拼接，不能自动等价替代 H3 时间轴适配。"}, label: "H3 长视频", description: "按计划与提示词表适配 H3 视频工作流。", category: "视频", legacy: { kind: "comfyui", adapter: "h3_long_video" }, inputs: [], outputs: [{ key: "applied_prompts", label: "已应用提示词", type: "json" }], config: [
    { key: "planRef", path: "comfyui.h3LongVideo.planRef", label: "分镜计划", type: "reference", required: true },
    { key: "promptRowsRef", path: "comfyui.h3LongVideo.promptRowsRef", label: "提示词表", type: "reference", required: true },
    { key: "referenceImagesRef", path: "comfyui.h3LongVideo.referenceImagesRef", label: "参考图片", type: "reference", required: true },
    { key: "materialNoteRef", path: "comfyui.h3LongVideo.materialNoteRef", label: "素材说明", type: "reference" },
  ], editor: { ...bindings, bindingTypes: [{ direction: "output", nodeType: "VHS_VideoCombine", property: "Filenames", type: "video_list" }] }, result: { renderer: "auto" } },
  { id: "comfyui.commerce_pack", version: "1", usage: {"tier":"specialized","compatibilityOnly":true,"whenToUse":"仅兼容已有电商图包快照和图包下载协议；新场景不再依赖此整包执行器。","basicAlternative":"新图包用 Hermes/文本模板 + ComfyUI（需要生成时）+ 图片画布与排版 + 通用逐项执行；平台尺寸/文案/清单作为配置和普通JSON输出。"}, label: "电商图包（旧版兼容）", description: "仅兼容旧图包流程和清单协议；排版已复用基础图片能力，新场景使用基础组合。", category: "图片", legacy: { kind: "comfyui", adapter: "commerce_pack" }, inputs: [], outputs: [{ key: "commerce_manifest", label: "图包清单", type: "json" }], config: [], editor: { ...bindings, inputs: "ports" }, result: { renderer: "auto" } },
  { id: "comfyui.long_text_video", version: "1", usage: {"tier":"specialized","whenToUse":"确实需要 H3 分镜时长/帧数校验、人物场景道具音色的逐镜素材映射和声音约束时使用；不是通用逐项生成的必需步骤。","basicAlternative":"普通分镜视频用 Hermes + 媒体引用选择 + ComfyUI 逐项绑定 + 本地视频拼接；只保留 H3 特有的帧网格、段落协议和原生音频规则适配。"}, label: "H3 原生有声适配", description: "保留旧 long_text_video 标识；适配 H3 帧数、六段提示词与原生声音规则。可选步骤输入prompts为按Writer分镜顺序排列的AIXG提示词字符串数组（1..360项，每项1..16000字），先全列表校验再只注入prompt，不修改Writer元数据；省略该输入保留旧inline prompt协议。逐项转换/执行复用基础Hermes与通用流程。", category: "视频", legacy: { kind: "comfyui", adapter: "long_text_video" }, inputs: [], outputs: [{ key: "applied_shot", label: "已应用镜头", type: "json" }], config: [], editor: { ...bindings, inputs: "ports", outputs: "ports", editablePorts: true }, result: { renderer: "auto" } },
  { id: "media.video_concat", version: "1", usage: {"tier":"basic","whenToUse":"把任意场景的视频片段按顺序本地合成并保留原声，不调用生成模型。"}, label: "本地视频拼接", description: "本机 FFmpeg 按顺序拼接片段，保留原生声音，不调用生成服务。", category: "视频", legacy: { kind: "comfyui", adapter: "video_concat" }, inputs: [], outputs: [], config: [], editor: ports, result: { renderer: "media" } },
];
