import ModalPortal from "./ModalPortal";
import { useEffect, useRef, useState } from "react";
import { Copy, FolderPlus, RefreshCw, ShieldCheck, Upload, X } from "lucide-react";
import { getAsset, listAssets, listAssetVersions, getAssetVersion, updateAsset, uploadAsset } from "../lib/api";
import { assetPreview, assetReference, categoryLabels, kindLabels } from "../lib/production";
import type { AssetKind, AssetReference } from "../../server/domain/productionContracts";
import type { AssetPage, AssetSummary, AssetVersionSummary } from "../../server/domain/assetLibraryContracts";
import { useModalFocus } from "../hooks/useModalFocus";
import AssetMetadataFields, { splitAssetTags, type AssetMetadataForm } from "./AssetMetadataFields";
import AssetWriteRecovery from "./AssetWriteRecovery";
export function AssetPreview({ asset, version = asset.currentVersion }: { asset: Pick<AssetSummary, "id" | "kind" | "name" | "currentVersion">; version?: number }) {
  const url = assetPreview(asset.id, version);
  return asset.kind === "video" ? <video src={url} controls preload="metadata" /> : asset.kind === "audio" ? <audio src={url} controls preload="metadata" /> : <img src={url} alt={asset.name} loading="lazy" />;
}
const metadata = (asset: AssetSummary): AssetMetadataForm => ({ name: asset.name, category: asset.category, description: asset.description, group: asset.group, tags: asset.tags.join("，") });
export default function AssetBrowser({ kind, onPick }: { kind?: AssetKind; onPick?: (reference: AssetReference) => void }) {
  const [page, setPage] = useState<AssetPage>(); const [search, setSearch] = useState("");
  const [category, setCategory] = useState(""); const [kindFilter, setKindFilter] = useState(kind ?? ""); const [group, setGroup] = useState(""); const [tag, setTag] = useState(""); const [archived, setArchived] = useState(false);
  const [cursor, setCursor] = useState<string>(); const [previous, setPrevious] = useState<Array<string | undefined>>([]); const [refresh, setRefresh] = useState(0);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<AssetSummary>();
  const [uploadFile, setUploadFile] = useState<File>(); const [uploadTarget, setUploadTarget] = useState<AssetSummary>();
  const uploadRef = useRef<HTMLInputElement>(null); const uploadFor = useRef<AssetSummary | undefined>(undefined);
  function reset() { setCursor(undefined); setPrevious([]); setRefresh(value => value + 1); }
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); setPage(undefined); const timer = setTimeout(() => {
    listAssets({ q: search, kind: kind ?? kindFilter, category, group, tag, archived, limit: 24, cursor }, controller.signal).then(setPage).catch(reason => { if (!controller.signal.aborted) setError(reason.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
  }, 150); return () => { clearTimeout(timer); controller.abort(); }; }, [search, category, kind, kindFilter, group, tag, archived, cursor, refresh]);
  function chooseFile(target?: AssetSummary) { uploadFor.current = target; uploadRef.current?.click(); }
  return <div className="production-assets">
    {!onPick && <><div className="asset-library-notice"><ShieldCheck size={15} /><span>仅管理员管理 · 说明与标签可供 AI 检索 · 使用时固定素材版本</span></div><AssetWriteRecovery onReconciled={reset} /></>}
    <div className="production-toolbar asset-search-toolbar"><input className="text-input" aria-label="搜索素材" placeholder="搜索名称、说明、分组、标签" value={search} onChange={event => { setSearch(event.target.value); reset(); }} />
      {!kind && <select aria-label="素材类型" value={kindFilter} onChange={event => { setKindFilter(event.target.value); reset(); }}><option value="">全部类型</option>{Object.entries(kindLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>}
      <select aria-label="素材分类" value={category} onChange={event => { setCategory(event.target.value); reset(); }}><option value="">全部分类</option>{Object.entries(categoryLabels).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select>
      <input className="text-input asset-filter-input" aria-label="按分组筛选" placeholder="精确分组" value={group} onChange={event => { setGroup(event.target.value); reset(); }} /><input className="text-input asset-filter-input" aria-label="按标签筛选" placeholder="精确标签" value={tag} onChange={event => { setTag(event.target.value); reset(); }} />
      {!onPick && <><label><input type="checkbox" checked={archived} onChange={event => { setArchived(event.target.checked); reset(); }} />包含已归档</label><button className="button button-outline" onClick={() => chooseFile()}><Upload size={14} />上传素材</button><input ref={uploadRef} type="file" hidden accept="image/*,video/*,audio/*" onChange={event => { const file = event.target.files?.[0]; if (file) { setUploadTarget(uploadFor.current); setUploadFile(file); } uploadFor.current = undefined; event.target.value = ""; }} /></>}
      <button className="icon-button" aria-label="刷新素材库" title="刷新素材库" disabled={loading} onClick={reset}><RefreshCw size={16} /></button>
    </div>
    {error && <div className="workflow-run-error" role="alert">{error} <button className="text-button" onClick={reset}>重新读取第一页</button></div>}
    {loading ? <p className="studio-field-hint" role="status">正在读取服务端素材…</p> : page?.assets.length ? <><div className="asset-page-summary">共 {page.total} 个素材 · 第 {previous.length + 1} 页 · 本页 {page.assets.length} 个</div><div className="production-asset-grid">{page.assets.map(asset => <article className={"production-asset-card" + (asset.archivedAt ? " archived" : "")} key={asset.id}><div className="production-asset-preview"><AssetPreview asset={asset} /></div><div className="production-asset-body"><strong>{asset.name}</strong><small>{categoryLabels[asset.category]} · {kindLabels[asset.kind]} · v{asset.currentVersion} / {asset.versionCount} 个版本{asset.archivedAt ? " · 已归档" : ""}{asset.group ? " · " + asset.group : ""}</small>{asset.description && <p className="asset-card-description" title={asset.description}>{asset.description}</p>}<div className="production-tags">{asset.tags.map((tag,index) => <span key={tag + index}>{tag}</span>)}</div><div className="production-toolbar"><button className="text-button" onClick={() => setEditing(asset)}>{onPick ? "查看 / 选择版本" : "详情 / 管理"}</button>{onPick && <button className="button button-outline" onClick={() => onPick(assetReference(asset))}>选用 v{asset.currentVersion}</button>}</div></div></article>)}</div><div className="asset-pagination"><button className="button button-outline" disabled={!previous.length} onClick={() => { setCursor(previous.at(-1)); setPrevious(values => values.slice(0, -1)); }}>上一页</button><span>第 {previous.length + 1} 页</span><button className="button button-outline" disabled={!page.hasMore} onClick={() => { setPrevious(values => [...values, cursor]); setCursor(page.nextCursor); }}>下一页</button></div></> : page && <div className="library-empty"><FolderPlus size={30} /><strong>{search || category || group || tag || kindFilter ? "没有符合条件的素材" : "素材库还是空的"}</strong><p>{onPick ? "请管理员先上传或收藏所需素材。" : "上传图片、视频或音频，或在运行结果中点击“存入素材库”。"}</p>{!onPick && <button className="button button-outline" onClick={() => chooseFile()}>上传第一个素材</button>}</div>}
    {editing && <AssetDetails key={editing.id} initial={editing} onPick={onPick} onClose={() => setEditing(undefined)} onChanged={reset} onUpload={chooseFile} />}
    {uploadFile && <AssetUploadDialog file={uploadFile} target={uploadTarget} onClose={() => setUploadFile(undefined)} onSaved={asset => { setUploadFile(undefined); setEditing(asset); reset(); }} />}
  </div>;
}
function AssetUploadDialog({ file, target, onClose, onSaved }: { file: File; target?: AssetSummary; onClose(): void; onSaved(asset: AssetSummary): void }) {
  const detected = file.type.startsWith("video/") ? "video" : file.type.startsWith("audio/") ? "audio" : file.type.startsWith("image/") ? "image" : /\.(mp4|mov|webm)$/i.test(file.name) ? "video" : /\.(wav|mp3|m4a|flac|ogg)$/i.test(file.name) ? "audio" : /\.(png|jpe?g|webp|gif|avif)$/i.test(file.name) ? "image" : undefined;
  const [form, setForm] = useState<AssetMetadataForm>(() => target ? metadata(target) : { name: file.name, category: "material", description: "", group: "", tags: "" });
  const [createId] = useState(() => crypto.randomUUID()); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const modal = useModalFocus(onClose, busy);
  const invalid = !detected ? "请选择图片、视频或音频文件" : target && target.kind !== detected ? "新版本必须与原素材类型一致" : !file.size || file.size > 250 * 1024 * 1024 ? "文件必须非空且不超过 250MB" : "";
  async function save() { if (!detected || invalid) return; setBusy(true); setError(""); try { const result = await uploadAsset(file, { ...form, tags: splitAssetTags(form.tags), kind: detected, ...(target ? { assetId: target.id, revision: target.revision } : { createId }) }); onSaved(result.asset); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  return <ModalPortal><div className="production-modal-backdrop"><section className="production-modal" ref={modal} role="dialog" aria-modal="true" aria-label="上传素材"><div className="production-toolbar"><h2>{target ? "上传新版本" : "上传素材"}</h2><button className="icon-button" aria-label="关闭素材上传" disabled={busy} onClick={onClose}><X size={18} /></button></div><p className="studio-field-hint">{file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB · 只上传归档，不触发生成</p><AssetMetadataFields value={form} kind={detected ?? "image"} disabled={busy} onChange={setForm} />{(invalid || error) && <div className="workflow-run-error" role="alert">{invalid || error}</div>}<button className="button button-primary" disabled={busy || !!invalid || !form.name.trim()} onClick={() => void save()}>{busy ? "上传归档中…" : target ? "保存新版本" : "上传并保存"}</button></section></div></ModalPortal>;
}
function AssetDetails({ initial, onPick, onClose, onChanged, onUpload }: { initial: AssetSummary; onPick?: (reference: AssetReference) => void; onClose(): void; onChanged(): void; onUpload(asset: AssetSummary): void }) {
  const [asset, setAsset] = useState(initial); const [form, setForm] = useState(() => metadata(initial)); const [versions, setVersions] = useState<AssetVersionSummary[]>([]); const [cursor, setCursor] = useState<string>();
  const [selectedVersion, setSelectedVersion] = useState(initial.currentVersion); const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [copied, setCopied] = useState(false); const [reload, setReload] = useState(0);
  const modal = useModalFocus(onClose, busy);
  useEffect(() => { const controller = new AbortController(); setBusy(true); setError(""); void (async () => { try { const fresh = await getAsset(initial.id, controller.signal); const page = await listAssetVersions(initial.id, { limit: 24 }, controller.signal); if (page.revision !== fresh.asset.revision) throw new Error("素材在加载期间变化，请重新读取详情"); if (!controller.signal.aborted) { setAsset(fresh.asset); setForm(metadata(fresh.asset)); setVersions(page.versions); setCursor(page.nextCursor); } } catch (reason) { if (!controller.signal.aborted) setError((reason as Error).message); } finally { if (!controller.signal.aborted) setBusy(false); } })(); return () => controller.abort(); }, [initial.id, initial.revision, reload]);
  useEffect(() => { setSelectedVersion(initial.currentVersion); setCopied(false); }, [initial.id, initial.currentVersion]);
  async function more() { setBusy(true); setError(""); try { const page = await listAssetVersions(asset.id, { cursor, limit: 24 }); if (page.revision !== asset.revision) throw new Error("版本历史已变化，请重新读取详情"); setVersions(values => [...values, ...page.versions]); setCursor(page.nextCursor); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function save(archived?: boolean) { setBusy(true); setError(""); try { const result = await updateAsset(asset.id, { revision: asset.revision, ...form, tags: splitAssetTags(form.tags), ...(archived === undefined ? {} : { archived }) }); setAsset(result.asset); setReload(value => value + 1); onChanged(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function copy() { try { await navigator.clipboard.writeText(JSON.stringify({ assetId: asset.id, assetVersion: selectedVersion })); setCopied(true); } catch { setError("无法自动复制，请手动复制下方固定版本引用"); } }
  return <ModalPortal><div className="production-modal-backdrop"><section className="production-modal production-modal-wide" ref={modal} role="dialog" aria-modal="true" aria-label="素材详情"><div className="production-toolbar"><h2>{asset.name}</h2><button className="icon-button" disabled={busy} aria-label="关闭素材详情" onClick={onClose}><X size={18} /></button></div><div className="production-detail-grid"><div><AssetPreview asset={asset} version={selectedVersion} /><label className="field-group"><span>固定版本（共 {asset.versionCount} 个）</span><select value={selectedVersion} disabled={busy} onChange={event => { setSelectedVersion(Number(event.target.value)); setCopied(false); }}>{versions.map(version => <option key={version.version} value={version.version}>v{version.version} · {new Date(version.createdAt).toLocaleString()}</option>)}</select></label>{cursor && <button className="text-button" disabled={busy} onClick={() => void more()}>加载更早版本</button>}<p className="studio-field-hint">{kindLabels[asset.kind]} · revision {asset.revision}{asset.archivedAt ? " · 已归档" : ""}</p><pre className="asset-fixed-reference">{JSON.stringify({ assetId: asset.id, assetVersion: selectedVersion }, null, 2)}</pre><button className="button button-outline" onClick={() => void copy()} disabled={busy}><Copy size={14} />{copied ? "已复制引用" : "复制 AI 固定版本引用"}</button>{onPick && <button className="button button-primary" disabled={busy || !versions.length} onClick={() => onPick(assetReference(asset, selectedVersion))}>选用此版本</button>}<AssetVersionDetails key={asset.id + ":" + selectedVersion} assetId={asset.id} version={selectedVersion} /></div><div>{onPick ? <><h3>素材说明</h3><p className="asset-full-description">{asset.description || "暂无说明"}</p><p>{asset.group}</p><div className="production-tags">{asset.tags.map((tag,index) => <span key={tag + index}>{tag}</span>)}</div></> : <><AssetMetadataFields value={form} kind={asset.kind} disabled={busy} onChange={setForm} /><div className="production-toolbar"><button className="button button-primary" disabled={busy || !form.name.trim()} onClick={() => void save()}>保存说明与元数据</button><button className="button button-outline" disabled={busy} onClick={() => onUpload(asset)}><Upload size={14} />上传新版本</button><button className="text-button" disabled={busy} onClick={() => void save(!asset.archivedAt)}>{asset.archivedAt ? "取消归档" : "归档素材"}</button></div><p className="studio-field-hint">归档只隐藏素材，不删除文件；已运行任务和已保存引用始终使用原版本。说明不会触发生成或发布。</p></>}{error && <div className="workflow-run-error" role="alert">{error}<button className="text-button" disabled={busy} onClick={() => setReload(value => value + 1)}>重新读取详情（放弃未保存编辑）</button></div>}</div></div></section></div></ModalPortal>;
}
function AssetVersionDetails({ assetId, version }: { assetId: string; version: number }) {
  const [detail, setDetail] = useState<AssetVersionSummary>(); const [text, setText] = useState(""); const [next, setNext] = useState<number>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const controller = useRef(new AbortController());
  useEffect(() => { const active = new AbortController(); controller.current = active; const signal = active.signal; getAssetVersion(assetId, version, {}, signal).then(result => setDetail(result.version)).catch(reason => { if (!signal.aborted) setError(reason.message); }); return () => active.abort(); }, [assetId, version]);
  async function read(offset = 0) { setBusy(true); setError(""); try { const result = await getAssetVersion(assetId, version, { includeParameters: true, parametersOffset: offset }, controller.current.signal); if (!controller.current.signal.aborted) { setText(value => offset ? value + (result.parameters?.text ?? "") : result.parameters?.text ?? ""); setNext(result.parameters?.nextOffset); } } catch (reason) { if (!controller.current.signal.aborted) setError((reason as Error).message); } finally { if (!controller.current.signal.aborted) setBusy(false); } }
  return <details className="asset-version-provenance"><summary>来源与生成参数（按需读取）</summary>{detail && <><p>文件：{detail.originalName} · {(detail.bytes / 1024).toFixed(1)} KB</p><pre>{JSON.stringify(detail.source ?? { source: "本地上传" }, null, 2)}</pre>{detail.parametersOmitted && !text && <button className="text-button" disabled={busy} onClick={() => void read()}>读取生成参数</button>}</>}{text && <pre>{text}</pre>}{next !== undefined && <button className="text-button" disabled={busy} onClick={() => void read(next)}>继续读取参数（尚未完整）</button>}{error && <p role="alert">{error}</p>}</details>;
}
export function AssetPickerDialog({ kind, onPick, onClose }: { kind: AssetKind; onPick(reference: AssetReference): void; onClose(): void }) {
  const modal = useModalFocus(onClose);
  return <ModalPortal><div className="production-modal-backdrop"><section className="production-modal production-modal-wide" ref={modal} role="dialog" aria-modal="true" aria-label="从素材库选择"><div className="production-toolbar"><h2>选择{kindLabels[kind]}素材</h2><button className="icon-button" aria-label="关闭素材选择" onClick={onClose}><X size={18} /></button></div><AssetBrowser kind={kind} onPick={reference => { onPick(reference); onClose(); }} /></section></div></ModalPortal>;
}
