import type { AssetCategory, AssetKind } from "../../server/domain/productionContracts";
import { categoryLabels } from "../lib/production";
export interface AssetMetadataForm { name: string; category: AssetCategory; description: string; group: string; tags: string }
export function compatibleCategories(kind: AssetKind) { return Object.entries(categoryLabels).filter(([key]) => key === "material" || (kind === "audio" ? key === "voice" : kind === "image" && key !== "voice")); }
export default function AssetMetadataFields({ value, kind, disabled, onChange }: { value: AssetMetadataForm; kind: AssetKind; disabled?: boolean; onChange(value: AssetMetadataForm): void }) {
  const change = (key: keyof AssetMetadataForm, next: string) => onChange({ ...value, [key]: next });
  return <><label className="field-group"><span>素材名称</span><input className="text-input" maxLength={160} value={value.name} disabled={disabled} onChange={event => change("name", event.target.value)} /></label><label className="field-group"><span>分类</span><select value={value.category} disabled={disabled} onChange={event => change("category", event.target.value)}>{compatibleCategories(kind).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="field-group"><span>素材说明（供 AI 检索与选用）</span><textarea className="text-input asset-description-input" rows={4} maxLength={4000} placeholder="描述画面/声音内容、适合的用途和使用限制；不会触发生成" value={value.description} disabled={disabled} onChange={event => change("description", event.target.value)} /></label><label className="field-group"><span>分组</span><input className="text-input" maxLength={160} placeholder="如项目名、角色名或用途" value={value.group} disabled={disabled} onChange={event => change("group", event.target.value)} /></label><label className="field-group"><span>标签（逗号分隔，最多 30 个）</span><input className="text-input" value={value.tags} disabled={disabled} onChange={event => change("tags", event.target.value)} /></label></>;
}
export const splitAssetTags = (value: string) => value.split(/[,，]/).map(item => item.trim()).filter(Boolean);
