import ModalPortal from "./ModalPortal";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, RefreshCw, X } from "lucide-react";
import type { WorkflowRunRecord } from "../types";
import type { ClipSelection, ClipCandidate, AssetSource } from "../../server/domain/productionContracts";
import { composeClipSelection, createClipSelection, listClipSelections, loadClipCandidates, loadClipSelection, updateClipSelection } from "../lib/api";
import { assetPreview } from "../lib/production";
import { useModalFocus } from "../hooks/useModalFocus";
export default function ClipSelectionDialog({ run, initialSelectionId, onClose, onComposed }: { run?: WorkflowRunRecord; initialSelectionId?: string; onClose(): void; onComposed(runId: string): void }) {
  const videoSteps = run?.workflow?.steps.filter(step => step.execution?.mode === "for_each" && step.outputs.some(output => /^(video|video_list)$/.test(output.type))) ?? [];
  const [stepId, setStepId] = useState(videoSteps[0]?.id ?? ""); const outputs = videoSteps.find(step => step.id === stepId)?.outputs.filter(output => /^(video|video_list)$/.test(output.type)) ?? [];
  const [outputKey, setOutputKey] = useState(outputs[0]?.key ?? ""); const [name, setName] = useState((run?.runTitle ?? run?.workflowName ?? "") + " · 选片");
  const [lists, setLists] = useState<ClipSelection[]>([]); const [selection, setSelection] = useState<ClipSelection | null>(null); const [candidates, setCandidates] = useState<Array<{ shotId: string; candidates: ClipCandidate[] }>>([]);
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [refresh, setRefresh] = useState(0); const [error, setError] = useState(""); const modal = useModalFocus(onClose,busy);
  useEffect(() => { const controller = new AbortController(); listClipSelections(run?.runId,controller.signal).then(async result => { if (controller.signal.aborted) return; setLists(result.selections); const id = initialSelectionId ?? result.selections[0]?.id; if (id) { const current = await loadClipSelection(id,controller.signal); if (!controller.signal.aborted) setSelection(current.selection); } }).catch(reason => { if (!controller.signal.aborted) setError(reason.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [run?.runId,initialSelectionId]);
  useEffect(() => { if (!selection) return; const controller = new AbortController(); setCandidates([]); loadClipCandidates(selection.id,controller.signal).then(result => setCandidates(result.shots)).catch(reason => { if (!controller.signal.aborted) setError(reason.message); }); return () => controller.abort(); }, [selection?.id,refresh]);
  function saved(value: ClipSelection) { setSelection(value); setLists(current => [value,...current.filter(item => item.id !== value.id)]); }
  async function create() { if (!run) return; setBusy(true); setError(""); try { const result = await createClipSelection({ sourceRunId:run.runId,stepId,outputKey,name }); saved(result.selection); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function choose(shotId: string, source: AssetSource) { if (!selection) return; setBusy(true); setError(""); try { const result = await updateClipSelection(selection.id,{ revision:selection.revision,shotId,source }); saved(result.selection); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function move(index: number,offset: number) { if (!selection) return; const order = selection.shots.map(shot => shot.shotId); [order[index],order[index+offset]] = [order[index+offset],order[index]]; setBusy(true); setError(""); try { const result = await updateClipSelection(selection.id,{ revision:selection.revision,shotOrder:order }); saved(result.selection); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function compose() { if (!selection) return; setBusy(true); setError(""); try { const result = await composeClipSelection(selection.id,selection.revision); saved(result.selection); onComposed(result.runId); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function reload() { if (!selection) return; setBusy(true); setError(""); try { const result = await loadClipSelection(selection.id); saved(result.selection); setRefresh(value => value+1); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  return <ModalPortal><div className="production-modal-backdrop"><section className="production-modal production-modal-wide" role="dialog" aria-modal="true" aria-label="镜头选版与合成" ref={modal}><div className="production-toolbar"><h2>镜头选版与合成</h2><button className="icon-button" onClick={onClose} disabled={busy} aria-label="关闭镜头选版"><X size={18} /></button></div><p className="studio-field-hint">每个镜头独立选择历史版本。新生成的候选不会覆盖已选版本；合成只运行本地 FFmpeg。</p>
    {loading ? <p>读取清单中…</p> : <><div className="production-toolbar"><select aria-label="选片清单" value={selection?.id ?? ""} disabled={busy} onChange={event => { const value = lists.find(item => item.id === event.target.value); if (value) saved(value); }}><option value="">选择已有清单</option>{lists.map(item => <option key={item.id} value={item.id}>{item.name} · {item.shots.length} 镜</option>)}</select>{selection && <button className="button button-outline" disabled={busy} onClick={() => void reload()}><RefreshCw size={14} />刷新候选 / 清单</button>}</div>
      {run && <details open={!lists.length}><summary>创建新的选片清单</summary><div className="production-toolbar"><input className="text-input" aria-label="清单名称" value={name} onChange={event => setName(event.target.value)} disabled={busy} /><select aria-label="选片视频步骤" value={stepId} disabled={busy} onChange={event => { setStepId(event.target.value); setOutputKey(videoSteps.find(step => step.id === event.target.value)?.outputs.find(output => /^(video|video_list)$/.test(output.type))?.key ?? ""); }}>{videoSteps.map(step => <option key={step.id} value={step.id}>{step.name}</option>)}</select><select aria-label="选片视频输出" value={outputKey} disabled={busy} onChange={event => setOutputKey(event.target.value)}>{outputs.map(output => <option key={output.key} value={output.key}>{output.label}</option>)}</select><button className="button button-outline" disabled={busy || !name.trim() || !outputKey} onClick={() => void create()}>创建清单</button></div></details>}
      {selection && <><p className="production-clip-meta">{selection.name} · 清单版本 {selection.revision} · 已选 {selection.shots.filter(shot => shot.choice).length}/{selection.shots.length} 镜</p>{selection.shots.map((shot,position) => { const choices = candidates.find(item => item.shotId === shot.shotId)?.candidates ?? []; return <section className="production-clip-row" key={shot.shotId}><div className="production-toolbar"><strong>第 {position+1} 镜（原镜头 {shot.index+1}）</strong><button className="icon-button" disabled={busy || position === 0} aria-label={"上移镜头 " + (position+1)} onClick={() => void move(position,-1)}><ArrowUp size={14} /></button><button className="icon-button" disabled={busy || position === selection.shots.length-1} aria-label={"下移镜头 " + (position+1)} onClick={() => void move(position,1)}><ArrowDown size={14} /></button></div><details><summary>查看该镜分镜内容</summary><pre>{JSON.stringify(shot.value,null,2)}</pre></details><div className="production-clip-candidates">
        {shot.choice?.assetId && <article className="production-clip-candidate selected"><strong>当前采用版本</strong><video controls preload="metadata" src={assetPreview(shot.choice.assetId,shot.choice.assetVersion!)} /><small>来源 {shot.choice.source.runId.slice(0,8)} · 素材 v{shot.choice.assetVersion}</small></article>}
        {choices.map(candidate => { const selected = Boolean(shot.choice && JSON.stringify(shot.choice.source) === JSON.stringify(candidate.source)); return <article className="production-clip-candidate" key={JSON.stringify(candidate.source)}><video src={candidate.previewUrl} controls preload="metadata" /><small>{candidate.runTitle}<br />{candidate.source.runId.slice(0,8)} · {new Date(candidate.createdAt).toLocaleString()}</small><button className="button button-outline" disabled={busy || selected} onClick={() => void choose(shot.shotId,candidate.source)}>{selected ? "已采用" : "采用这一版"}</button></article>; })}
        {!choices.length && <p className="production-clip-meta">暂无匹配候选。只匹配同一修订链且分镜内容一致的结果，不会把同序号的另一镜误套进来。</p>}
      </div></section>; })}<button className="button button-primary" disabled={busy || selection.shots.some(shot => !shot.choice)} onClick={() => void compose()}>{busy ? "提交中…" : "按已选版本合成"}</button><p className="studio-field-hint">已选片段保存在独立素材归档中；不会重新调用 Writer 或视频生成模型。</p></>}
    </>}{error && <div className="workflow-run-error" role="alert">{error}</div>}
  </section></div></ModalPortal>;
}
