/** Compiled backend + real stdio MCP. Temporary data/project; local condition only. */
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/client";
import { StdioClientTransport } from "@modelcontextprotocol/client/stdio";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const temporary=await mkdtemp(path.join(os.tmpdir(),"zane-access-smoke-"));const project=path.join(temporary,"project");await mkdir(project);let child;let exited;const clients=[];let logs="";
const bounded=(promise,ms=15000)=>Promise.race([promise,new Promise((_,reject)=>{const timer=setTimeout(()=>reject(new Error("Access smoke timeout\n"+logs.slice(-2000))),ms);timer.unref();})]);
try {
  child=spawn(process.execPath,[path.join(root,"dist-server/index.js"),"--production"],{cwd:root,windowsHide:true,stdio:["ignore","pipe","pipe"],env:{...process.env,ZANE_ADMIN_TOKEN:"",ZANE_API_TOKEN:"",ZANE_PUBLIC_USER_PORT:"",API_HOST:"127.0.0.1",API_PORT:"0",APP_DATA_DIR:path.join(temporary,"data"),ZANE_PROJECT_DIR:project,HERMES_HOME:path.join(temporary,"no-hermes"),COMFYUI_BASE_URL:"http://127.0.0.1:1",ZANE_SHUTDOWN_TIMEOUT_MS:"1000"}});
  exited=new Promise(resolve=>child.once("exit",resolve));const base=await bounded(new Promise((resolve,reject)=>{child.once("error",reject);child.once("exit",code=>reject(new Error("Backend exit "+code+"\n"+logs)));child.stderr.on("data",chunk=>logs+=chunk);child.stdout.on("data",chunk=>{logs+=chunk;const match=/server listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(logs);if(match)resolve(match[1]);});}));
  const http=async(route,token="",body,method=body===undefined ? "GET" : "POST")=>{const response=await fetch(base+route,{method,headers:{...(token ? {Authorization:"Bearer "+token} : {}),...(body===undefined ? {} : {"Content-Type":"application/json"})},body:body===undefined ? undefined : JSON.stringify(body)});return {response,data:await response.json()};};
  assert.equal((await http("/api/workspace")).response.status,401);
  const password="temporary-access-password-2026";const setup=await http("/api/auth/setup","",{userId:randomUUID(),username:"smokeadmin",displayName:"临时管理员",password,role:"admin"});assert.equal(setup.response.status,201);const adminToken=/zane_session=([^;]+)/.exec(setup.response.headers.get("set-cookie"))[1];
  async function connect(token) {const transport=new StdioClientTransport({command:process.execPath,args:[path.join(root,"dist-server/mcp/index.js")],cwd:root,env:{...process.env,ZANE_BASE_URL:base,ZANE_API_TOKEN:token},stderr:"pipe"});const client=new Client({name:"access-smoke",version:"1"});transport.stderr?.on("data",chunk=>logs+=chunk);clients.push(client);await bounded(client.connect(transport));return {client,call:async(name,args={})=>(await bounded(client.callTool({name,arguments:args}))).structuredContent};}
  const admin=await connect(adminToken);const scene={id:"access-smoke",title:"用户授权场景",summary:"仅本地条件，不调用模型"};const workflow={sceneId:scene.id,name:scene.title,inputs:[{key:"flag",label:"条件开关",type:"boolean",required:true,defaultValue:true}],steps:[{id:"check",name:"本地条件",kind:"control",control:{type:"condition",match:"all",rules:[{id:"rule",leftRef:"input.flag",operator:"equals",valueSource:"literal",rightValue:"true",rightRef:""}]},outputs:[{key:"result",label:"条件结果",type:"boolean"}]}],outputs:[{key:"result",label:"结果",type:"boolean",sourceRef:"step.check.outputs.result"}]};
  const created=await admin.call("create_scene",{scene,workflow});assert.equal(created.ok,true);const publicationId=randomUUID();assert.equal((await admin.call("publish_scene",{sceneId:scene.id,revision:created.data.revision,publicationId})).ok,true);
  const userId=randomUUID();assert.equal((await admin.call("create_user",{userId,username:"ordinary",displayName:"普通用户",password})).ok,true);const login=await http("/api/auth/login","",{username:"ordinary",password});const session=/zane_session=([^;]+)/.exec(login.response.headers.get("set-cookie"))[1];const minted=await http("/api/v1/self/tokens",session,{tokenId:randomUUID(),name:"smoke MCP"});assert.equal(minted.response.status,201);const user=await connect(minted.data.token);
  assert.deepEqual((await user.call("list_available_scenes")).data.items,[]);assert.equal((await user.call("get_workspace")).error.code,"ADMIN_REQUIRED");assert.equal((await admin.call("set_user_scene_access",{userId,revision:1,sceneIds:[scene.id]})).ok,true);const available=await user.call("get_available_scene",{sceneId:scene.id});assert.equal(available.ok,true);assert.equal(available.data.versionId,publicationId);assert.ok(!("workflow" in available.data));
  const doctor=spawn(process.execPath,[path.join(root,"scripts/check-ai-access.mjs")],{cwd:root,windowsHide:true,env:{...process.env,ZANE_BASE_URL:base,ZANE_API_TOKEN:minted.data.token},stdio:["ignore","pipe","pipe"]});
  let doctorOutput="",doctorErrors="";doctor.stdout.on("data",chunk=>doctorOutput+=chunk);doctor.stderr.on("data",chunk=>doctorErrors+=chunk);
  try {const code=await bounded(new Promise((resolve,reject)=>{doctor.once("error",reject);doctor.once("exit",resolve);}));assert.equal(code,0,doctorErrors);const report=JSON.parse(doctorOutput);assert.equal(report.mode,"user");assert.equal(report.userId,userId);assert.equal(report.ready,true);assert.equal(report.generationExecuted,false);} finally {if(doctor.exitCode===null)doctor.kill();}
  const draftId=randomUUID();assert.equal((await user.call("save_own_draft",{draftId,revision:0,sceneId:scene.id,versionId:publicationId,title:"本人输入",inputValues:{flag:true}})).ok,true);assert.equal((await user.call("get_own_draft",{draftId})).data.draft.revision,1);
  const runId=randomUUID();assert.equal((await user.call("prepare_own_scene",{sceneId:scene.id,versionId:publicationId,inputValues:{flag:true}})).ok,true);assert.equal((await user.call("submit_own_scene",{sceneId:scene.id,versionId:publicationId,inputValues:{flag:true},runId})).ok,true);
  let completed=false;for(let i=0;i<60;i++){const run=await user.call("get_own_run",{runId});if(run.data.status==="completed"){completed=true;break;}await new Promise(resolve=>setTimeout(resolve,50));}assert.ok(completed);assert.equal((await user.call("get_own_outputs",{runId})).data.outputs[0].value,true);assert.equal((await user.call("submit_own_scene",{sceneId:scene.id,versionId:publicationId,inputValues:{flag:true},runId})).error.code,"RUN_ALREADY_EXISTS");
  const detail=(await user.call("get_own_run",{runId})).data;assert.equal(detail.progress.completed,1);assert.equal(detail.progress.total,1);assert.equal(detail.versionId,publicationId);assert.ok(detail.startedAt && detail.revision);
  const inputSnapshot=await user.call("get_own_run_inputs",{runId,inputKey:"flag"});assert.equal(inputSnapshot.ok,true);assert.equal(inputSnapshot.data.snapshot,"recorded_run");assert.equal(inputSnapshot.data.inputs[0].value,true);
  const inputMeta=await user.call("get_own_run_inputs",{runId,includeValues:false});assert.equal(inputMeta.data.inputs[0].omissionReason,"metadata_only");
  const activity=await user.call("get_own_run_activity",{runId,limit:1});assert.equal(activity.ok,true);assert.equal(activity.data.events[0].type,"run.queued");assert.equal(activity.data.hasMore,true);
  const activityNext=await user.call("get_own_run_activity",{runId,limit:1,afterSequence:activity.data.nextSequence});assert.ok(activityNext.data.nextSequence>activity.data.nextSequence);
  const another=(await admin.call("create_user",{userId:randomUUID(),username:"another",displayName:"另一个用户",password})).data.user;const otherLogin=await http("/api/auth/login","",{username:another.username,password});const otherToken=/zane_session=([^;]+)/.exec(otherLogin.response.headers.get("set-cookie"))[1];assert.equal((await http("/api/v1/self/runs/"+runId,otherToken)).response.status,404);assert.deepEqual((await http("/api/v1/self/runs",otherToken)).data.items,[]);
  for(const route of ["/api/workspace","/api/settings","/api/v1/users","/api/workflows/runs","/api/comfyui/view?filename=not-real"])assert.equal((await http(route,session)).response.status,403,route);
  const file=path.join(temporary,"test.png");await writeFile(file,Buffer.from([137,80,78,71,13,10,26,10]));const assetId=randomUUID();assert.equal((await user.call("upload_own_asset",{assetId,filePath:file,name:"test.png",kind:"image"})).ok,true);const asset=await user.call("get_own_asset",{assetId});assert.equal(asset.data.reference.assetId,assetId);assert.equal((await fetch(base+asset.data.reference.previewUrl,{method:"HEAD",headers:{Authorization:"Bearer "+otherToken}})).status,404);assert.equal((await fetch(base+asset.data.reference.previewUrl,{headers:{Authorization:"Bearer "+session,Range:"bytes=0-3"}})).status,206);
  assert.equal((await admin.call("set_user_scene_access",{userId,revision:2,sceneIds:[]})).ok,true);assert.equal((await user.call("prepare_own_scene",{sceneId:scene.id,versionId:publicationId,inputValues:{flag:true}})).error.code,"SCENE_ACCESS_DENIED");assert.equal((await user.call("get_own_run",{runId})).data.status,"completed");
  const resource=await user.client.readResource({uri:"zane://scenes"});assert.deepEqual(JSON.parse(resource.contents[0].text).data.items,[]);
  console.log("Access smoke passed: compiled backend + administrator/user real stdio MCP + own draft/run/asset + user read-only doctor + HTTP isolation; no external generation");
} finally {
  for(const client of clients)await client.close().catch(()=>{});
  if(child && child.exitCode===null){child.kill("SIGTERM");try{await bounded(exited,6000);}catch{child.kill("SIGKILL");await bounded(exited,3000);}}
  const resolved=path.resolve(temporary);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep+"zane-access-smoke-"));await rm(resolved,{recursive:true,force:true});
}
