import { useEffect, useState } from "react";
import App from "./App";
import UserPortal from "./features/UserPortal";
import { accessApi, jsonBody, setCurrentActor, type Account } from "./lib/accessApi";
export default function Application() {
  const [publicOnly,setPublicOnly] = useState(false); const [user,setUser] = useState<Account>(); const [initialized,setInitialized] = useState<boolean>(); const [loading,setLoading] = useState(true); const [busy,setBusy] = useState(false); const [error,setError] = useState(""); const [username,setUsername] = useState(""); const [displayName,setDisplayName] = useState(""); const [password,setPassword] = useState(""); const [setupId] = useState(()=>crypto.randomUUID()); const [mode,setMode] = useState<"admin"|"user">("admin");
  function accept(account:Account) {const mode = account.role === "admin" && window.location.pathname !== "/app" ? "admin" : "user";setError("");setCurrentActor(account.id);setUser(account);setMode(mode);window.history.replaceState(null,"",mode === "admin" ? "/admin" : "/app");}
  useEffect(()=>{let stopped=false;setCurrentActor("");void (async()=>{try {const status=await accessApi<{initialized:boolean;entryMode?:"full"|"user-only"}>("/api/auth/status");if(stopped)return;setInitialized(status.initialized);setPublicOnly(status.entryMode === "user-only");if(status.initialized){try {const result=await accessApi<{user:Account}>("/api/v1/self/account");if(!stopped)accept(result.user);}catch(e){if(!stopped && (e as {status?:number}).status!==401)setError((e as Error).message);}}}catch(e){if(!stopped)setError((e as Error).message);}finally{if(!stopped)setLoading(false);}})();const invalid=()=>{setUser(undefined);setCurrentActor("");setPassword("");setInitialized(true);};window.addEventListener("zane-auth-required",invalid);return()=>{stopped=true;window.removeEventListener("zane-auth-required",invalid);};},[]);
  async function login() {setBusy(true);setError("");try {const result=await accessApi<{user:Account}>(initialized ? "/api/auth/login" : "/api/auth/setup",jsonBody(initialized ? {username,password} : {userId:setupId,username,displayName,password,role:"admin"}));setPassword("");setInitialized(true);accept(result.user);}catch(e){setError((e as Error).message+(!initialized ? "；若首次初始化回执丢失，请改为登录，不要重复创建。" : ""));}finally{setBusy(false);} }
  async function logout(){try{await accessApi("/api/v1/self/logout",jsonBody({}));setUser(undefined);setCurrentActor("");setPassword("");window.history.replaceState(null,"",publicOnly ? "/app" : "/");}catch(e){setError((e as Error).message);} }
  if(loading)return <div className="access-login"><section className="access-card"><h1>正在连接 Zane Studio</h1><p>读取服务端登录状态…</p></section></div>;
  if(user)return <>{error && <p role="alert" className="access-error access-session-alert">{error}</p>}{user.role === "admin" && mode === "admin" ? <App key={user.id} userId={user.id} displayName={user.displayName} onLogout={()=>void logout()} onOpenUserView={()=>{setMode("user");window.history.replaceState(null,"","/app");}} /> : <UserPortal key={user.id} user={user} onLogout={()=>void logout()} onAdmin={user.role === "admin" && !publicOnly ? ()=>{setMode("admin");window.history.replaceState(null,"","/admin");} : undefined} />}</>;
  if(publicOnly && initialized === false)return <div className="access-login"><section className="access-card"><h1>用户服务尚未开放</h1><p>请联系管理员在私有入口完成初始化并分配账户，此入口不提供管理员初始化。</p>{error && <p role="alert" className="access-error">{error}</p>}</section></div>;
  return <div className="access-login"><section className="access-card"><p className="eyebrow">ZANE STUDIO</p><h1>{initialized === false ? "初始化管理员" : "登录创作系统"}</h1><p>{initialized === false ? "在服务器本机创建首个管理员。现有场景和历史数据会保留，不创建用户工作区。" : publicOnly ? "仅供普通用户登录，使用已授权的发布场景。管理员请使用私有入口。" : "管理员进入管理后台，普通用户进入授权场景使用页面。"}</p>{error && <p role="alert" className="access-error">{error}</p>}<form onSubmit={e=>{e.preventDefault();void login();}}><label>登录名<input className="text-input" autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required /></label>{initialized === false && <label>显示名<input className="text-input" value={displayName} onChange={e=>setDisplayName(e.target.value)} required /></label>}<label>密码<input className="text-input" type="password" autoComplete={initialized ? "current-password" : "new-password"} value={password} onChange={e=>setPassword(e.target.value)} minLength={initialized ? 1 : 10} required /></label><button className="button button-dark" disabled={busy || initialized === undefined}>{busy ? "处理中…" : initialized ? "登录" : "创建管理员"}</button></form><button className="access-link" onClick={()=>void accessApi<{initialized:boolean;entryMode?:"full"|"user-only"}>("/api/auth/status").then(result=>{setInitialized(result.initialized);setPublicOnly(result.entryMode === "user-only");setError("");}).catch(e=>setError((e as Error).message))}>刷新初始化状态 / 对账后登录</button></section></div>;
}
