/** Response contracts for the access surface; shared by OpenAPI and regression tests. */
const text = {type:"string"}; const integer = {type:"integer"}; const obj = {type:"object",additionalProperties:true};
const ref = (name:string) => ({$ref:"#/components/schemas/"+name});
const schema = (required:string[],properties:Record<string,unknown>) => ({type:"object",required,properties,additionalProperties:false});
const counts = schema(["total","completed","skipped","failed","cancelled","running","pending"],{total:integer,completed:integer,skipped:integer,failed:integer,cancelled:integer,running:integer,pending:integer});
const valuePage = schema(["kind","total","offset","count","pageSize","complete","hasMore"],{kind:{enum:["string","array","object","scalar"]},total:integer,offset:integer,count:integer,pageSize:integer,complete:{type:"boolean"},hasMore:{type:"boolean"},nextValueOffset:integer});
const page = (item:string) => schema(["items","hasMore"],{items:{type:"array",items:ref(item)},hasMore:{type:"boolean"},total:integer,revision:text,nextCursor:text,catalogView:{const:"published"},nextAction:text});
export const ACCESS_RESPONSE_SCHEMAS = {
  EntrySecurity:schema(["contractVersion","entryMode","setupAvailable","administratorCredentials","errors","loginRateLimit"],{contractVersion:{const:"1.0.0"},entryMode:{enum:["full","user-only"]},setupAvailable:{type:"boolean"},administratorCredentials:{enum:["allowed","rejected"]},errors:{const:"redacted_on_public_or_production"},loginRateLimit:schema(["windowSeconds","accountAttempts","sourceAttempts","maxConcurrent","persistence","counted","source"],{windowSeconds:{type:"number",minimum:1,maximum:86400},accountAttempts:{type:"integer",minimum:1,maximum:1000},sourceAttempts:{type:"integer",minimum:1,maximum:10000},maxConcurrent:{type:"integer",minimum:1,maximum:64},persistence:{const:"process-local"},counted:{const:"all_attempts"},source:{const:"verified_request_ip"}})}),
  AuthStatus:schema(["initialized","nextAction","entryMode","setupAllowed","security"],{initialized:{type:"boolean"},nextAction:{enum:["login","setup_admin","contact_admin"]},entryMode:{enum:["full","user-only"]},setupAllowed:{type:"boolean"},security:ref("EntrySecurity")}),
  AuthLogout:schema(["loggedOut"],{loggedOut:{const:true}}),
  UserAccount:schema(["id","revision","username","displayName","role","enabled","sceneIds","createdAt","updatedAt"],{id:text,revision:{type:"integer",minimum:1},username:text,displayName:text,role:{enum:["admin","user"]},enabled:{type:"boolean"},sceneIds:{type:"array",items:text},createdAt:text,updatedAt:text}),
  UserEnvelope:schema(["user"],{user:ref("UserAccount"),nextAction:text,sessionsRevoked:{type:"boolean"}}),
  UserPage:page("UserAccount"),
  AvailableScene:schema(["id","revision","sceneId","title","summary","versionId","version"],{id:text,revision:integer,sceneId:text,title:text,summary:text,versionId:text,version:text}),
  AvailableScenePage:page("AvailableScene"),
  UserScene:schema(["sceneId","title","summary","description","versionId","version","fields","inputDefaults","inputSchema","notices","nextAction"],{sceneId:text,title:text,summary:text,description:text,versionId:text,version:text,fields:{type:"array",items:schema(["key","label","type","required","hidden","placeholder"],{key:text,label:text,type:text,required:{type:"boolean"},hidden:{type:"boolean",description:"网页输入表单是否隐藏；字段仍可由接口显式提交并参与流程执行"},minimum:{type:"number",description:"number类型的包含下限"},maximum:{type:"number",description:"number类型的包含上限"},placeholder:text,options:{type:"array",items:text},inputMode:{enum:["object_array"]},itemFields:{type:"array",items:schema(["key","label","type","required"],{key:text,label:text,type:{enum:["text","number","boolean","select"]},required:{type:"boolean"},minimum:{type:"number"},maximum:{type:"number"},placeholder:text,options:{type:"array",items:text}})}})},inputDefaults:obj,inputSchema:obj,notices:{type:"array",items:text},nextAction:text}),
  UserPreparation:schema(["valid","sceneId","versionId","externalServicesChecked","nextAction"],{valid:{const:true},sceneId:text,versionId:text,externalServicesChecked:{const:false},nextAction:text}),
  UserDraft:schema(["id","revision","userId","sceneId","versionId","title","updatedAt","isFavorite"],{id:text,revision:integer,userId:text,sceneId:text,versionId:text,title:text,updatedAt:text,isFavorite:{type:"boolean",description:"收藏置顶，旧草稿默认false；收藏不改变updatedAt"},inputValues:obj,inputValuesOmitted:{const:true}}),
  UserDraftEnvelope:schema(["draft"],{draft:ref("UserDraft"),nextAction:text}),
  UserDraftPage:page("UserDraft"),
  RunProgress:schema(["total","completed","skipped","failed","cancelled","running","pending","settled"],{...counts.properties,settled:integer}),
  UserRunStep:schema(["stepId","order","name","status","inputCount","outputCount","expectedOutputCount","reused","replaced"],{stepId:text,order:integer,name:text,status:{enum:["pending","running","completed","skipped","failed","cancelled"]},startedAt:{...text,description:"步骤实际开始时间；running时可与当前时间相减显示实时用时"},durationMs:{...integer,description:"步骤实际执行用时；for_each为整个步骤的墙钟时间，不含人工审核等待；旧运行可能没有"},inputCount:integer,outputCount:integer,expectedOutputCount:integer,warningCount:{...integer,description:"步骤及逐项非阻断提示总数；按get_own_step_result分页读取warnings正文"},itemProgress:counts,reviewStatus:{enum:["pending","approved"]},reused:{type:"boolean"},replaced:{type:"boolean"}}),
  UserRun:schema(["runId","sceneId","workflowName","status","createdAt","steps","progress","inputCount","outputCount","expectedOutputCount","reviewCount","projection","revision","nextAction"],{runId:text,sceneId:text,workflowName:text,versionId:text,version:text,publishedAt:text,runTitle:text,status:ref("RunStatus"),createdAt:text,startedAt:{...text,description:"首次持久化run.started事件时间；没有事件则省略，不用queued占位startedAt"},finishedAt:text,queueDurationMs:integer,totalDurationMs:{...integer,description:"结束减创建，包含排队和审核等待，不是模型执行计时"},steps:{type:"array",items:ref("UserRunStep")},progress:ref("RunProgress"),pendingReview:ref("PendingReview"),error:text,inputCount:integer,outputCount:integer,expectedOutputCount:integer,reviewCount:integer,projection:{const:"business"},revision:text,nextAction:text,timedOut:{type:"boolean"}}),
  UserRunInput:schema(["key","label","type","required","present","valueBytes","valuePage"],{key:text,label:text,type:text,required:{type:"boolean"},minimum:{type:"number",description:"记录运行快照的包含下限"},maximum:{type:"number",description:"记录运行快照的包含上限"},present:{type:"boolean"},value:{description:"可分段的业务值；媒体只返回固定assetId/assetVersion"},valueBytes:integer,valueOmitted:{const:true},omissionReason:{enum:["metadata_only","value_byte_limit"]},nextAction:text,valuePage}),
  UserRunInputPage:schema(["runId","revision","projection","snapshot","inputs","total","hasMore","nextAction"],{runId:text,revision:text,projection:{const:"business"},snapshot:{const:"recorded_run"},inputs:{type:"array",items:ref("UserRunInput")},total:integer,hasMore:{type:"boolean"},nextCursor:text,nextAction:text}),
  UserRunActivity:schema(["sequence","type","at"],{sequence:integer,type:{enum:["run.queued","run.recovered_queued","run.started","run.completed","run.failed","run.cancelled","run.cancelling","run.stale","run.waiting","step.started","step.completed","step.failed","step.skipped","step.cancelled","step.item.started","step.item.completed","step.item.failed","step.item.skipped","step.item.cancelled","review.approve","review.redo"]},at:text,stepId:text,stepName:text,itemIndex:integer}),
  UserRunActivityPage:schema(["runId","projection","events","nextSequence","hasMore","nextAction"],{runId:text,projection:{const:"business"},events:{type:"array",items:ref("UserRunActivity")},nextSequence:integer,hasMore:{type:"boolean"},nextAction:text}),
  UserRunPage:page("UserRun"),
  UserToken:schema(["id","revision","name","createdAt","expiresAt","revoked"],{id:text,revision:integer,name:text,createdAt:text,expiresAt:text,revoked:{type:"boolean"}}),
  UserTokenPage:page("UserToken"),
  UserTokenCreated:schema(["user","token","credential","nextAction"],{user:ref("UserAccount"),token:{type:"string",description:"仅创建回执返回一次的敏感密钥；丢失后不能回读"},credential:ref("UserToken"),nextAction:text}),
  UserTokenRevoked:schema(["credential","nextAction"],{credential:ref("UserToken"),nextAction:text}),
  UserAsset:schema(["id","revision","name","kind","currentVersion"],{id:text,revision:integer,name:text,kind:{enum:["image","video","audio"]},currentVersion:integer}),
  UserAssetEnvelope:schema(["asset","reference"],{asset:ref("UserAsset"),reference:obj,nextAction:text}),
  OwnAssetSummary:schema(["id","revision","name","category","kind","description","group","tags","createdAt","updatedAt","currentVersion","versionCount","versionsOmitted","reference"],{id:text,revision:integer,name:text,category:{enum:["character","scene","prop","voice","material"]},kind:{enum:["image","video","audio"]},description:text,group:text,tags:{type:"array",items:text},createdAt:text,updatedAt:text,archivedAt:text,currentVersion:integer,versionCount:integer,versionsOmitted:{const:true},reference:schema(["assetId","assetVersion"],{assetId:text,assetVersion:{type:"integer",minimum:1},assetName:text,previewUrl:text})}),
  OwnAssetPage:schema(["schemaVersion","catalogRevision","assets","total","hasMore","nextAction"],{schemaVersion:{const:1},catalogRevision:text,assets:{type:"array",items:ref("OwnAssetSummary")},total:integer,hasMore:{type:"boolean"},nextCursor:text,nextAction:{const:"get_own_asset"}}),
};
export const ACCESS_OUTPUT_TYPES: Record<string,string> = {
  get_current_user:"UserEnvelope",list_users:"UserPage",get_user:"UserEnvelope",create_user:"UserEnvelope",update_user:"UserEnvelope",set_user_scene_access:"UserEnvelope",reset_user_password:"UserEnvelope",
  list_available_scenes:"AvailableScenePage",get_available_scene:"UserScene",prepare_own_scene:"UserPreparation",submit_own_scene:"UserRun",list_own_drafts:"UserDraftPage",get_own_draft:"UserDraftEnvelope",save_own_draft:"UserDraftEnvelope",set_own_draft_favorite:"UserDraftEnvelope",list_own_runs:"UserRunPage",get_own_run:"UserRun",get_own_run_inputs:"UserRunInputPage",get_own_run_activity:"UserRunActivityPage",wait_own_run:"UserRun",cancel_own_run:"UserRun",review_own_run:"UserRun",resume_own_run:"UserRun",get_own_outputs:"RunOutputPage",get_own_step_result:"StepResult",list_own_assets:"OwnAssetPage",upload_own_asset:"UserAssetEnvelope",get_own_asset:"UserAssetEnvelope",list_own_tokens:"UserTokenPage",create_own_token:"UserTokenCreated",revoke_own_token:"UserTokenRevoked",
};
